#line 2 "probeconfscan.c"

#line 4 "probeconfscan.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define yy_create_buffer probeconfscan__create_buffer
#define yy_delete_buffer probeconfscan__delete_buffer
#define yy_flex_debug probeconfscan__flex_debug
#define yy_init_buffer probeconfscan__init_buffer
#define yy_flush_buffer probeconfscan__flush_buffer
#define yy_load_buffer_state probeconfscan__load_buffer_state
#define yy_switch_to_buffer probeconfscan__switch_to_buffer
#define yyin probeconfscan_in
#define yyleng probeconfscan_leng
#define yylex probeconfscan_lex
#define yylineno probeconfscan_lineno
#define yyout probeconfscan_out
#define yyrestart probeconfscan_restart
#define yytext probeconfscan_text
#define yywrap probeconfscan_wrap
#define yyalloc probeconfscan_alloc
#define yyrealloc probeconfscan_realloc
#define yyfree probeconfscan_free

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
typedef uint64_t flex_uint64_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;
#endif /* ! C99 */

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE probeconfscan_restart(probeconfscan_in  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#define YY_BUF_SIZE 16384
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern yy_size_t probeconfscan_leng;

extern FILE *probeconfscan_in, *probeconfscan_out;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up probeconfscan_text. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up probeconfscan_text again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	yy_size_t yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via probeconfscan_restart()), so that the user can continue scanning by
	 * just pointing probeconfscan_in at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when probeconfscan_text is formed. */
static char yy_hold_char;
static yy_size_t yy_n_chars;		/* number of characters read into yy_ch_buf */
yy_size_t probeconfscan_leng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow probeconfscan_wrap()'s to do buffer switches
 * instead of setting up a fresh probeconfscan_in.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void probeconfscan_restart (FILE *input_file  );
void probeconfscan__switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE probeconfscan__create_buffer (FILE *file,int size  );
void probeconfscan__delete_buffer (YY_BUFFER_STATE b  );
void probeconfscan__flush_buffer (YY_BUFFER_STATE b  );
void probeconfscan_push_buffer_state (YY_BUFFER_STATE new_buffer  );
void probeconfscan_pop_buffer_state (void );

static void probeconfscan_ensure_buffer_stack (void );
static void probeconfscan__load_buffer_state (void );
static void probeconfscan__init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER probeconfscan__flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE probeconfscan__scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE probeconfscan__scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE probeconfscan__scan_bytes (yyconst char *bytes,yy_size_t len  );

void *probeconfscan_alloc (yy_size_t  );
void *probeconfscan_realloc (void *,yy_size_t  );
void probeconfscan_free (void *  );

#define yy_new_buffer probeconfscan__create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        probeconfscan_ensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            probeconfscan__create_buffer(probeconfscan_in,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        probeconfscan_ensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            probeconfscan__create_buffer(probeconfscan_in,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

FILE *probeconfscan_in = (FILE *) 0, *probeconfscan_out = (FILE *) 0;

typedef int yy_state_type;

extern int probeconfscan_lineno;

int probeconfscan_lineno = 1;

extern char *probeconfscan_text;
#define yytext_ptr probeconfscan_text

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up probeconfscan_text.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	probeconfscan_leng = (yy_size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 68
#define YY_END_OF_BUFFER 69
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[459] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,   69,   35,    3,    6,
       35,    4,   35,   35,   35,   35,   35,   35,   35,   35,
       35,   35,   50,    3,   45,   47,   48,    5,   49,   47,
       44,    3,   68,   44,   44,   44,   52,    3,   51,   52,
        3,   53,   67,    3,   59,   58,   68,    2,    2,    1,
        2,    3,   56,   57,   68,   57,   57,    3,    6,    4,
        0,    0,    4,    4,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        3,   45,    5,   47,    5,    5,   47,    3,    0,    0,

        0,   52,    3,   52,   51,   52,   52,    3,   53,   67,
        3,   66,   65,   63,   64,   60,   62,   61,    3,    1,
        0,    0,    0,    3,   56,    0,   57,    0,    0,   57,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
       47,    0,    0,    0,   57,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,   47,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,   15,    0,    0,    0,    0,    0,    0,    0,    0,

       29,    0,    0,    0,    0,    0,   47,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,   21,    0,    0,    0,    0,    0,   31,
        0,   34,    0,   47,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,   16,    0,
        0,   21,    0,    0,    0,    0,    0,    0,    0,   47,
        0,    0,    0,    0,    0,    0,    0,    9,    0,    0,
        0,    0,    0,    0,    0,    0,   20,    0,    0,    0,
        0,   28,   30,    0,    0,   47,    0,    0,    0,    0,
        0,    0,    8,    0,    0,    0,    0,   12,   13,    0,

        0,    0,    0,    0,    0,   26,    0,    0,    0,   46,
        0,    0,    0,    0,    0,    0,    0,    8,    0,    0,
        0,    0,   14,    0,    0,   17,    0,    0,   17,    0,
       18,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,   55,    7,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,   41,    0,    0,    0,    0,
       54,    0,    7,    0,    0,    0,   37,    0,    0,    0,
        0,    0,    0,    0,    0,   41,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,   38,    0,    0,    0,    0,    0,   36,    0,   22,

       23,    0,   27,   32,   33,   38,    0,    0,    0,   43,
        0,    0,    0,    0,    0,    0,    0,   43,   10,    0,
       19,    0,    0,    0,    0,   40,    0,    0,    0,    0,
        0,   40,    0,    0,    0,    0,    0,   11,    0,    0,
        0,   42,    0,    0,    0,   42,    0,   25,   39,    0,
       39,    0,    0,    0,    0,    0,   24,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        2,    2,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    6,    4,    4,    4,    1,    4,
        4,    4,    4,    7,    8,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    9,    4,    4,    4,    4,   10,   11,   12,   13,

       14,   15,   16,   17,   18,    4,   19,   20,   21,   22,
       23,   24,   25,   26,   27,   28,   29,   30,   31,   32,
       33,    4,    4,    4,    4,    4,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[34] =
    {   0,
        1,    1,    2,    3,    4,    1,    1,    3,    5,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3
    } ;

static yyconst flex_int16_t yy_base[481] =
    {   0,
        0,    0,   33,   59,   84,  110,  137,  144,  151,  158,
       39,   44,   48,   65,  165,  179,  914,  915,   67,  915,
      905,   53,   64,   66,   35,   37,   69,   80,   81,   29,
       67,   87,  915,   76,  915,    0,  915,   97,  915,  898,
      915,  909,  915,  888,  895,  885,    0,  103,    0,  112,
      114,  915,    0,  905,  915,  915,  191,  915,  116,  915,
      122,  124,  915,    0,  126,  915,  884,  129,  915,  131,
      897,   84,  171,  173,  175,  128,  161,  182,  154,  184,
      189,  181,  183,  191,  195,  193,  190,  210,  201,  196,
      224,  915,  219,    0,  226,  229,  883,  901,  869,  874,

      871,    0,  231,  233,    0,  236,  238,  240,  915,    0,
      897,  915,  915,  915,  915,  915,  915,  915,  242,  915,
      244,  247,  249,  251,  915,  253,    0,  256,  258,  885,
      254,  255,  256,  113,  257,  264,  259,  260,  263,  265,
      889,  266,  888,  267,  274,  275,  276,  282,  271,  281,
      885,  886,  865,  866,  889,  283,  285,  291,  284,  206,
      296,  299,  292,  301,  302,  297,  309,  304,  314,  882,
      305,  311,  313,  316,  881,  326,  329,  870,  869,  868,
      873,  337,  332,  334,  336,  335,  337,  340,  858,  857,
      868,  873,  342,   75,  344,  343,  349,  350,  360,  354,

      872,  367,  353,  368,  361,  374,  857,  367,  856,  863,
      862,  369,  373,  385,  867,  390,  377,  851,  850,  850,
      389,  394,  386,  398,  863,  400,  393,  399,  405,  862,
      404,  861,  860,  854,  838,  854,  854,  855,  840,  345,
      406,  407,  408,  409,  853,  831,  848,  831,  427,  412,
      411,  849,  431,  428,  414,  413,  423,  425,  434,  842,
      841,  834,  825,  834,  824,  437,  442,  842,  443,  445,
      462,  825,  834,  824,  844,  451,  837,  449,  452,  454,
      458,  836,  835,  456,  459,  816,  815,  817,  821,  460,
      815,  463,  460,  471,  475,  470,  480,  915,  915,  811,

      487,  497,  477,  828,  827,  826,  493,  825,  487,    0,
      817,  819,  807,  801,  817,  801,  495,  818,  498,  488,
      500,  499,  915,  509,  514,  915,  519,  521,  525,  517,
      817,  521,  522,  506,  534,  523,  814,  804,  800,  807,
      800,  530,  510,  811,  810,  536,  535,  545,  540,  548,
      551,  552,  554,  553,  805,  789,  807,  788,  790,  562,
      915,  564,  804,  561,  562,  569,  803,  573,  574,  579,
      580,  581,  575,  582,  796,  915,  791,  793,  795,  589,
      597,  586,  589,  594,  596,  598,  602,  603,  604,  605,
      608,  779,  593,  795,  785,  606,  610,  795,  614,  794,

      793,  792,  791,  790,  789,  915,  768,  768,  757,  729,
      612,  615,  616,  639,  732,  721,  719,  915,  717,  621,
      684,  626,  628,  665,  667,  662,  624,  633,  647,  673,
      675,  915,  623,  648,  645,  675,  665,  671,  652,  631,
      666,  649,  640,  653,  660,  915,  366,  170,  121,  659,
      915,  657,  660,  663,  661,  665,   44,  915,  693,  698,
      703,  708,  713,  718,  721,  726,  729,  734,  739,  744,
      749,  754,  757,  762,  765,  770,  775,  780,  785,  790
    } ;

static yyconst flex_int16_t yy_def[481] =
    {   0,
      458,    1,  459,  459,  460,  460,  461,  461,  461,  461,
      462,  462,  463,  463,  464,  464,  458,  458,  458,  458,
      465,  466,  465,  465,  465,  465,  465,  465,  465,  465,
      465,  465,  458,  458,  458,  467,  458,  468,  458,  467,
      458,  458,  458,  458,  458,  458,  469,  469,  470,  471,
      469,  458,  472,  472,  458,  458,  473,  458,  458,  458,
      474,  458,  458,  475,  476,  458,  475,  458,  458,  466,
      465,  465,  466,  466,  465,  465,  465,  465,  465,  465,
      465,  465,  465,  465,  465,  465,  465,  465,  465,  465,
      458,  458,  468,  467,  468,  468,  467,  458,  458,  458,

      458,  469,  469,  471,  470,  471,  471,  469,  458,  472,
      472,  458,  458,  458,  458,  458,  458,  458,  458,  458,
      474,  474,  474,  458,  458,  476,  475,  476,  476,  475,
      465,  465,  465,  465,  465,  465,  465,  465,  465,  465,
      465,  465,  465,  465,  465,  465,  465,  465,  465,  465,
      467,  458,  458,  458,  475,  465,  465,  465,  465,  465,
      465,  458,  465,  465,  465,  465,  465,  465,  465,  465,
      465,  465,  465,  465,  465,  465,  465,  467,  458,  458,
      458,  458,  465,  465,  465,  465,  465,  465,  458,  458,
      458,  465,  465,  465,  465,  465,  465,  465,  465,  465,

      465,  465,  465,  465,  465,  465,  467,  458,  458,  458,
      458,  465,  465,  465,  465,  465,  465,  458,  458,  458,
      465,  465,  465,  465,  465,  465,  465,  465,  465,  465,
      465,  465,  465,  467,  458,  458,  458,  458,  458,  465,
      465,  465,  465,  465,  465,  458,  458,  458,  465,  465,
      465,  465,  465,  465,  465,  465,  465,  465,  465,  467,
      458,  458,  458,  458,  458,  465,  465,  465,  465,  465,
      465,  458,  458,  458,  477,  465,  465,  465,  465,  465,
      465,  465,  465,  465,  465,  467,  458,  458,  458,  458,
      458,  465,  465,  465,  465,  465,  465,  458,  458,  458,

      478,  479,  465,  465,  465,  465,  465,  465,  465,  467,
      458,  458,  458,  458,  458,  458,  465,  465,  465,  465,
      465,  465,  458,  478,  478,  458,  478,  479,  478,  465,
      465,  465,  465,  465,  465,  465,  458,  458,  458,  458,
      458,  458,  465,  465,  465,  465,  465,  465,  465,  465,
      465,  465,  465,  465,  458,  458,  458,  458,  458,  458,
      458,  480,  465,  465,  465,  465,  465,  465,  465,  465,
      465,  465,  465,  465,  458,  458,  458,  458,  458,  480,
      480,  465,  465,  465,  465,  465,  465,  465,  465,  465,
      465,  458,  458,  458,  458,  465,  465,  465,  465,  465,

      465,  465,  465,  465,  465,  458,  458,  458,  458,  458,
      465,  465,  465,  465,  458,  458,  458,  458,  465,  465,
      465,  465,  465,  458,  458,  458,  465,  465,  465,  458,
      458,  458,  465,  465,  465,  458,  458,  465,  465,  465,
      458,  458,  465,  465,  458,  458,  465,  465,  458,  465,
      458,  465,  465,  465,  465,  465,  465,    0,  458,  458,
      458,  458,  458,  458,  458,  458,  458,  458,  458,  458,
      458,  458,  458,  458,  458,  458,  458,  458,  458,  458
    } ;

static yyconst flex_int16_t yy_nxt[949] =
    {   0,
       18,   19,   20,   21,   18,   22,   18,   21,   21,   23,
       21,   21,   24,   25,   21,   26,   21,   27,   21,   28,
       21,   21,   21,   29,   30,   31,   32,   21,   21,   21,
       21,   21,   21,   33,   34,   35,   72,   37,   38,   39,
       54,   55,   72,   56,   72,   54,   55,   57,   56,   59,
       60,   72,   57,   61,   74,   69,   78,   87,   40,   33,
       34,   35,   79,   37,   38,   39,   59,   60,   68,   69,
       61,   72,   70,   72,   72,   75,   72,   91,   92,   76,
       88,   93,   72,   77,   40,   42,   43,   72,   72,  222,
       80,   72,   81,   44,   72,   82,   45,   83,   96,   92,

       89,  131,   84,   85,  103,   69,   86,  132,  104,   90,
       46,   42,   43,  107,   69,  108,  109,  119,  120,   44,
       72,  121,   45,  123,  120,  124,  125,  129,  125,  126,
       68,   69,   74,   69,   70,   72,   46,   47,   48,   20,
      160,   47,   50,   47,   47,   48,   20,  451,   47,   50,
       47,   47,   51,   52,  134,   47,   47,   47,   47,   51,
       52,   72,   47,   47,   47,   43,   62,   63,   72,   43,
       65,   66,   74,   69,   74,   69,  137,   72,   67,   43,
       62,   63,   72,   43,   65,   66,  133,  135,   72,   72,
       72,   72,   67,  113,  136,  138,   72,   72,   72,  140,

       72,  114,   72,   72,  141,  115,  143,  147,   72,  142,
      145,  139,  116,   72,  144,  146,  117,   72,  118,  148,
       96,   92,  149,  187,  150,   91,   92,   96,   92,   93,
       96,   92,  103,   69,  107,   69,  104,  107,   69,  107,
       69,  108,  109,  119,  120,  123,  120,  121,  123,  120,
      123,  120,  124,  125,  129,  125,  126,  129,  125,  129,
      125,   72,   72,   72,   72,  162,   72,   72,  161,  159,
       72,   72,   72,   72,   72,  156,  165,  157,   72,  164,
      158,   72,   72,   72,  166,  172,  170,  163,   72,   72,
       72,   72,   72,  168,  175,  184,  171,  176,   72,   72,

      162,  174,  173,   72,   72,  188,  177,  186,   72,   72,
      183,   72,   72,  185,  189,  192,   72,  197,   72,  195,
       72,   72,  190,   72,  201,  191,  196,  194,  198,  193,
      200,  131,  132,   72,  203,  202,   72,  132,  182,   72,
      206,   72,   72,   72,   72,  212,  214,   72,  205,   72,
       72,   72,   72,  213,  221,  223,   72,   72,  216,  266,
       72,   72,  215,  211,  156,  217,  224,   72,   72,  226,
      225,  228,  227,  450,   72,   72,   72,  131,  229,  230,
       72,   72,  231,  132,   72,  131,  232,  233,  235,  245,
      236,  132,   72,   72,  240,  241,   72,   72,  242,  244,

       72,   72,  249,  250,  251,   72,   72,   72,  184,  254,
      255,   72,   72,   72,   72,   72,   72,  267,   72,   72,
       72,   72,  269,  276,  252,  131,  256,  257,  275,  258,
       72,  132,   72,  268,   72,   72,  270,  277,   72,  281,
      278,   72,  283,  280,   72,  282,  292,  284,  131,   72,
       72,  131,   72,  279,  132,  285,   72,  132,   72,   72,
      293,   72,  295,   72,  303,   72,   72,   72,  294,   72,
       72,  307,  309,  305,  317,  304,  308,   72,   72,  131,
      306,  314,   72,  315,  330,  132,  318,   72,  325,  326,
      296,  321,  297,  319,   72,   72,  322,  320,  328,  329,

       72,  324,   72,  331,  334,   72,   72,   72,  343,  345,
      325,  326,  347,   72,  336,  325,  326,   72,  344,  346,
      325,  326,  328,  329,   72,  324,  325,  326,   72,   72,
       72,  360,  361,  352,  131,  362,  363,  349,  131,  131,
      132,   72,   72,   72,  132,  350,  348,   72,  353,  366,
      351,  131,   72,  354,  368,   72,  367,  132,   72,   72,
       72,   72,  369,  360,  361,  381,  361,  362,   72,   72,
      370,  373,  371,  158,  372,  374,   72,  382,  131,  131,
       72,   72,   72,  383,  132,  132,   72,   72,   72,   72,
      381,  361,  385,   72,  390,  384,   72,  388,  381,  361,

      386,   72,  397,   72,  387,   72,  389,  391,  396,   72,
       72,   72,   72,   72,  407,   72,  408,   72,  404,   72,
      398,   72,   72,   72,  399,  400,  405,  413,   72,  401,
       72,   72,  411,   72,  402,   72,  403,  412,   72,  419,
       72,  438,  421,  427,  444,  420,   72,   72,  428,  433,
      429,  422,   72,  434,   72,   72,  131,  439,  435,   72,
       72,  447,  132,  440,   72,  423,   72,   72,   72,  443,
       72,  454,   72,  449,  456,  446,  131,  445,   72,  453,
      448,  455,  132,  442,  441,  452,  437,  436,  432,  431,
      430,   72,  457,   36,   36,   36,   36,   36,   41,   41,

       41,   41,   41,   49,   49,   49,   49,   49,   53,   53,
       53,   53,   53,   58,   58,   58,   58,   58,   64,   64,
       64,   64,   64,   71,   72,   71,   73,   73,   73,   73,
       73,   94,  426,   94,   95,   95,   95,   95,   95,  102,
      425,  102,  102,  102,  105,  424,  105,  105,  105,  106,
      106,  106,  106,  106,  110,  418,  110,  112,  112,  112,
      112,  112,  122,  122,  122,  122,  122,  127,  417,  127,
      128,  128,  128,  128,  128,  301,  301,  301,  416,  301,
      324,  324,  324,  324,  324,  327,  327,  327,  327,  327,
      380,  380,  380,  380,  380,  415,   72,   72,   72,  414,

       72,   72,   72,  410,  409,  406,  395,  394,  393,  392,
       72,   72,  379,  378,  377,  376,  375,  365,  364,  359,
      358,  357,  356,  355,   72,   72,  342,  341,  340,  339,
      338,  337,  335,   72,  333,  332,  323,  316,  313,  312,
      311,  310,   72,   72,   72,  302,  300,  299,  298,   72,
      291,  290,  289,  288,  287,  286,   72,  274,  273,  272,
      271,  265,  264,  263,  262,  261,  260,  259,   72,   72,
      253,  248,  247,  246,  243,  239,  238,  237,  234,   72,
       72,  220,  219,  218,  210,  209,  208,  207,  204,  199,
      182,  181,  180,  179,  178,  169,  167,  155,  111,  154,

      153,  152,   98,  151,   72,  130,  111,  101,  100,   99,
       98,   97,   72,  458,   17,  458,  458,  458,  458,  458,
      458,  458,  458,  458,  458,  458,  458,  458,  458,  458,
      458,  458,  458,  458,  458,  458,  458,  458,  458,  458,
      458,  458,  458,  458,  458,  458,  458,  458
    } ;

static yyconst flex_int16_t yy_chk[949] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    3,    3,    3,   30,    3,    3,    3,
       11,   11,   25,   11,   26,   12,   12,   11,   12,   13,
       13,  457,   12,   13,   22,   22,   25,   30,    3,    4,
        4,    4,   26,    4,    4,    4,   14,   14,   19,   19,
       14,   23,   19,   24,   31,   23,   27,   34,   34,   24,
       31,   34,  194,   24,    4,    5,    5,   28,   29,  194,
       27,   72,   27,    5,   32,   27,    5,   28,   38,   38,

       32,   72,   28,   29,   48,   48,   29,   72,   48,   32,
        5,    6,    6,   50,   50,   51,   51,   59,   59,    6,
      134,   59,    6,   61,   61,   62,   62,   65,   65,   62,
       68,   68,   70,   70,   68,   76,    6,    7,    7,    7,
      134,    7,    7,    7,    8,    8,    8,  449,    8,    8,
        8,    9,    9,    9,   76,    9,    9,    9,   10,   10,
       10,   79,   10,   10,   10,   15,   15,   15,   77,   15,
       15,   15,   73,   73,   74,   74,   79,  448,   15,   16,
       16,   16,   75,   16,   16,   16,   75,   77,   82,   78,
       83,   80,   16,   57,   78,   80,   81,   87,   84,   81,

       86,   57,   85,   90,   82,   57,   84,   87,   89,   83,
       86,   80,   57,  160,   85,   86,   57,   88,   57,   88,
       93,   93,   89,  160,   90,   91,   91,   95,   95,   91,
       96,   96,  103,  103,  104,  104,  103,  106,  106,  107,
      107,  108,  108,  119,  119,  121,  121,  119,  122,  122,
      123,  123,  124,  124,  126,  126,  124,  128,  128,  129,
      129,  131,  132,  133,  135,  136,  137,  138,  135,  133,
      139,  136,  140,  142,  144,  131,  139,  131,  149,  138,
      132,  145,  146,  147,  140,  146,  144,  137,  150,  148,
      156,  159,  157,  142,  148,  157,  145,  149,  158,  163,

      162,  147,  146,  161,  166,  161,  150,  159,  164,  165,
      156,  168,  171,  158,  162,  163,  167,  168,  172,  166,
      173,  169,  162,  174,  172,  162,  167,  165,  169,  164,
      171,  169,  167,  176,  174,  173,  177,  169,  182,  183,
      177,  184,  186,  185,  187,  183,  185,  188,  176,  193,
      196,  195,  240,  184,  193,  195,  197,  198,  187,  240,
      203,  200,  186,  182,  196,  188,  196,  199,  205,  198,
      197,  200,  199,  447,  202,  204,  212,  199,  202,  203,
      213,  206,  204,  199,  217,  204,  205,  206,  208,  217,
      208,  204,  214,  223,  212,  213,  221,  216,  214,  216,

      227,  222,  221,  222,  223,  224,  228,  226,  224,  226,
      227,  231,  229,  241,  242,  243,  244,  241,  251,  250,
      256,  255,  243,  250,  224,  243,  228,  229,  249,  231,
      257,  243,  258,  242,  249,  254,  244,  251,  253,  255,
      253,  259,  257,  254,  266,  256,  266,  258,  253,  267,
      269,  259,  270,  253,  253,  259,  278,  259,  276,  279,
      267,  280,  270,  284,  276,  281,  285,  293,  269,  271,
      292,  281,  285,  279,  292,  278,  284,  296,  294,  271,
      280,  290,  295,  290,  303,  271,  293,  297,  301,  301,
      271,  296,  271,  294,  309,  320,  297,  295,  302,  302,

      307,  302,  317,  303,  307,  319,  322,  321,  317,  320,
      324,  324,  322,  334,  309,  325,  325,  343,  319,  321,
      327,  327,  328,  328,  330,  328,  329,  329,  332,  333,
      336,  342,  342,  334,  330,  342,  343,  332,  332,  333,
      330,  335,  347,  346,  332,  333,  330,  349,  335,  346,
      333,  335,  348,  336,  348,  350,  347,  335,  351,  352,
      354,  353,  349,  360,  360,  362,  362,  360,  364,  365,
      350,  353,  351,  350,  352,  354,  366,  364,  364,  365,
      368,  369,  373,  365,  364,  365,  370,  371,  372,  374,
      380,  380,  368,  382,  373,  366,  383,  371,  381,  381,

      369,  384,  383,  385,  370,  386,  372,  374,  382,  387,
      388,  389,  390,  396,  393,  391,  393,  397,  390,  411,
      384,  399,  412,  413,  385,  386,  391,  399,  420,  387,
      433,  427,  396,  422,  388,  423,  389,  397,  440,  411,
      428,  433,  413,  420,  440,  412,  414,  443,  422,  427,
      423,  414,  435,  428,  429,  434,  414,  434,  429,  439,
      444,  443,  414,  435,  452,  414,  450,  453,  455,  439,
      454,  453,  456,  445,  455,  442,  450,  441,  438,  452,
      444,  454,  450,  437,  436,  450,  431,  430,  426,  425,
      424,  421,  456,  459,  459,  459,  459,  459,  460,  460,

      460,  460,  460,  461,  461,  461,  461,  461,  462,  462,
      462,  462,  462,  463,  463,  463,  463,  463,  464,  464,
      464,  464,  464,  465,  419,  465,  466,  466,  466,  466,
      466,  467,  417,  467,  468,  468,  468,  468,  468,  469,
      416,  469,  469,  469,  470,  415,  470,  470,  470,  471,
      471,  471,  471,  471,  472,  410,  472,  473,  473,  473,
      473,  473,  474,  474,  474,  474,  474,  475,  409,  475,
      476,  476,  476,  476,  476,  477,  477,  477,  408,  477,
      478,  478,  478,  478,  478,  479,  479,  479,  479,  479,
      480,  480,  480,  480,  480,  407,  405,  404,  403,  402,

      401,  400,  398,  395,  394,  392,  379,  378,  377,  375,
      367,  363,  359,  358,  357,  356,  355,  345,  344,  341,
      340,  339,  338,  337,  331,  318,  316,  315,  314,  313,
      312,  311,  308,  306,  305,  304,  300,  291,  289,  288,
      287,  286,  283,  282,  277,  275,  274,  273,  272,  268,
      265,  264,  263,  262,  261,  260,  252,  248,  247,  246,
      245,  239,  238,  237,  236,  235,  234,  233,  232,  230,
      225,  220,  219,  218,  215,  211,  210,  209,  207,  201,
      192,  191,  190,  189,  181,  180,  179,  178,  175,  170,
      155,  154,  153,  152,  151,  143,  141,  130,  111,  101,

      100,   99,   98,   97,   71,   67,   54,   46,   45,   44,
       42,   40,   21,   17,  458,  458,  458,  458,  458,  458,
      458,  458,  458,  458,  458,  458,  458,  458,  458,  458,
      458,  458,  458,  458,  458,  458,  458,  458,  458,  458,
      458,  458,  458,  458,  458,  458,  458,  458
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int probeconfscan__flex_debug;
int probeconfscan__flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *probeconfscan_text;
#line 1 "probeconfscan.l"
#line 2 "probeconfscan.l"
/*
** Copyright (C) 2005-2014 by Carnegie Mellon University.
**
** @OPENSOURCE_HEADER_START@
**
** Use of the SILK system and related source code is subject to the terms
** of the following licenses:
**
** GNU Public License (GPL) Rights pursuant to Version 2, June 1991
** Government Purpose License Rights (GPLR) pursuant to DFARS 252.227.7013
**
** NO WARRANTY
**
** ANY INFORMATION, MATERIALS, SERVICES, INTELLECTUAL PROPERTY OR OTHER
** PROPERTY OR RIGHTS GRANTED OR PROVIDED BY CARNEGIE MELLON UNIVERSITY
** PURSUANT TO THIS LICENSE (HEREINAFTER THE "DELIVERABLES") ARE ON AN
** "AS-IS" BASIS. CARNEGIE MELLON UNIVERSITY MAKES NO WARRANTIES OF ANY
** KIND, EITHER EXPRESS OR IMPLIED AS TO ANY MATTER INCLUDING, BUT NOT
** LIMITED TO, WARRANTY OF FITNESS FOR A PARTICULAR PURPOSE,
** MERCHANTABILITY, INFORMATIONAL CONTENT, NONINFRINGEMENT, OR ERROR-FREE
** OPERATION. CARNEGIE MELLON UNIVERSITY SHALL NOT BE LIABLE FOR INDIRECT,
** SPECIAL OR CONSEQUENTIAL DAMAGES, SUCH AS LOSS OF PROFITS OR INABILITY
** TO USE SAID INTELLECTUAL PROPERTY, UNDER THIS LICENSE, REGARDLESS OF
** WHETHER SUCH PARTY WAS AWARE OF THE POSSIBILITY OF SUCH DAMAGES.
** LICENSEE AGREES THAT IT WILL NOT MAKE ANY WARRANTY ON BEHALF OF
** CARNEGIE MELLON UNIVERSITY, EXPRESS OR IMPLIED, TO ANY PERSON
** CONCERNING THE APPLICATION OF OR THE RESULTS TO BE OBTAINED WITH THE
** DELIVERABLES UNDER THIS LICENSE.
**
** Licensee hereby agrees to defend, indemnify, and hold harmless Carnegie
** Mellon University, its trustees, officers, employees, and agents from
** all claims or demands made against them (and any related losses,
** expenses, or attorney's fees) arising out of, or relating to Licensee's
** and/or its sub licensees' negligent use or willful misuse of or
** negligent conduct or willful misconduct regarding the Software,
** facilities, or other rights or assistance granted by Carnegie Mellon
** University under this License, including, but not limited to, any
** claims of product liability, personal injury, death, damage to
** property, or violation of any laws or regulations.
**
** Carnegie Mellon University Software Engineering Institute authored
** documents are sponsored by the U.S. Department of Defense under
** Contract FA8721-05-C-0003. Carnegie Mellon University retains
** copyrights in all material produced under this contract. The U.S.
** Government retains a non-exclusive, royalty-free license to publish or
** reproduce these documents, or allow others to do so, for U.S.
** Government purposes only pursuant to the copyright license under the
** contract clause at 252.227.7013.
**
** @OPENSOURCE_HEADER_END@
*/

/*
**  Tokenizer for probe configuration file.
**
*/

#include <silk/silk.h>

RCSIDENT("$SiLK: probeconfscan.l cd598eff62b9 2014-09-21 19:31:29Z mthomas $");

#include "probeconfscan.h"
#include "probeconfparse.h"


/* TYPEDEFS AND DEFINES */

typedef struct pcscan_file_st {
    YY_BUFFER_STATE state;
    char           *name;
    FILE           *fp;
    int             line;
} pcscan_file_t;


/* EXPORTED VARIABLES */

/* Global error count for return status of skpcParse */
int pcscan_errors;

/* keyword we read; for printing messages in the parser. */
char pcscan_clause[128];

int (*extra_sensor_verify_fn)(skpc_sensor_t *sensor) = NULL;


/* LOCAL FUNCTION PROTOTYPES */

static int stash(int tok);
static void err_bad_line(int is_id);
static void err_include_arg(void);
static char *get_name(const char *s, int c);
static void filter_start(char unless_when);
static int filter_set_type(char filter_type, char list_type);

/* support for "include" */
static pcscan_file_t pcscan_stack[PCSCAN_MAX_INCLUDE_DEPTH];

/* next stack position */
static int pcscan_stack_depth = 0;

/* current pointer into pcscan_stack[] */
static pcscan_file_t *pcscan_file = NULL;

/* local buffer for reading quoted strings */
#define BUF_SIZE 2048
static char pcscan_buf[BUF_SIZE];
static char *pcscan_buf_end = pcscan_buf + BUF_SIZE - 1;
static char *pcscan_buf_ptr;

/* Check that we're not overflowing the buffer */
#define STRING_CHECK                            \
    if ( pcscan_buf_ptr >= pcscan_buf_end ) {   \
        skpcParseErr("String too long");        \
        BEGIN(ST_ERR);                          \
        return ERR_STR_TOO_LONG;                \
    }

SK_DIAGNOSTIC_IGNORE_PUSH("-Wwrite-strings")

#define YY_NO_INPUT 1
/* %option noyyget_extra noyyset_extra noyyget_leng noyyget_text */
/* %option noyyget_lineno noyyset_lineno noyyget_in noyyset_in */
/* %option noyyget_out noyyset_out noyyget_lval noyyset_lval */
/* %option noyyget_lloc noyyset_lloc noyyget_debug noyyset_debug */
/* ST_ARGS state says we have read a keyword and are parsing the
* arguments */

/* ST_FILTER state is used to read the token following a
* 'discard-unless' or 'discard-when' key word */

/* ST_ERR state is for an unrecognized keyword at start of line;
* reads to EOL.  Does not return any token to parser */

/* ST_ARG_ERR state is for an unrecognized keyword within a
* statement---that is, after having returned a token to the
* parser.  It reads to EOL and returns an EOL to the parser so
* that the parser can put itself into a good state. */

/* ST_STRING state is for processing quoted strings */

/* ST_NEWLINE state is used when a newline is read.  One purpose
* is to delay incrementing the line count until after the parser
* has processed the line---so errors are reported on correct
* line.  A second purpose is to detect when the file does not
* have a final newline. */

/* ST_IGNORE_SENSOR state is used to ignore the sensor statements
* (when parsing a file for flowcap) */

/* basic character classes */
/* An id must match keywords and sensor names as well as
* pathnames, hostnames, and IP addresses.  Allow any
* non-whitespace printable character other than " ' # , */
/* whitespace; we ignore it */
/* comment; ignore */
/* newline, maybe preceded by whitespace */
/* end of line, maybe preceded by comment; increment line count */
#line 989 "probeconfscan.c"

#define INITIAL 0
#define ST_ARGS 1
#define ST_FILTER 2
#define ST_ERR 3
#define ST_ARG_ERR 4
#define ST_STRING 5
#define ST_NEWLINE 6
#define ST_IGNORE_SENSOR 7

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int probeconfscan_lex_destroy (void );

int probeconfscan_get_debug (void );

void probeconfscan_set_debug (int debug_flag  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int probeconfscan_wrap (void );
#else
extern int probeconfscan_wrap (void );
#endif
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO fwrite( probeconfscan_text, probeconfscan_leng, 1, probeconfscan_out )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		yy_size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( probeconfscan_in )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( probeconfscan_in ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, probeconfscan_in))==0 && ferror(probeconfscan_in)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(probeconfscan_in); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int probeconfscan_lex (void);

#define YY_DECL int probeconfscan_lex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after probeconfscan_text and probeconfscan_leng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 207 "probeconfscan.l"


    /* ST_NEWLINE state: increment the line-count for the newline we
     * saw at the end of the previous statement.  Stay in the
     * ST_NEWLINE state if this line contains a comment or whitespace.
     * Otherwise, go into the INITIAL state by reading a character
     * then putting it back. */

#line 1165 "probeconfscan.c"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! probeconfscan_in )
			probeconfscan_in = stdin;

		if ( ! probeconfscan_out )
			probeconfscan_out = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			probeconfscan_ensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				probeconfscan__create_buffer(probeconfscan_in,YY_BUF_SIZE );
		}

		probeconfscan__load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of probeconfscan_text. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 459 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_current_state != 458 );
		yy_cp = (yy_last_accepting_cpos);
		yy_current_state = (yy_last_accepting_state);

yy_find_action:
		yy_act = yy_accept[yy_current_state];

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
/* rule 1 can match eol */
YY_RULE_SETUP
#line 215 "probeconfscan.l"
{ ++pcscan_file->line; }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 216 "probeconfscan.l"
{ yyless(0); ++pcscan_file->line;
                                          BEGIN(INITIAL); }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 219 "probeconfscan.l"
;
	YY_BREAK
/* handle comment at end of file with no trailing newline */
case 4:
YY_RULE_SETUP
#line 223 "probeconfscan.l"
{ BEGIN(ST_NEWLINE); }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 224 "probeconfscan.l"
{ BEGIN(ST_ERR); }
	YY_BREAK
/* read first keyword on a line */
case 6:
/* rule 6 can match eol */
YY_RULE_SETUP
#line 228 "probeconfscan.l"
{ BEGIN(ST_NEWLINE);}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 230 "probeconfscan.l"
{ yylval.string = get_name(probeconfscan_text,'-');
                                          return stash(NET_NAME_INTERFACE); }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 233 "probeconfscan.l"
{ yylval.string = get_name(probeconfscan_text,'-');
                                          return stash(NET_NAME_IPBLOCK); }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 236 "probeconfscan.l"
{ yylval.string = get_name(probeconfscan_text,'-');
                                          return stash(PROBES); }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 239 "probeconfscan.l"
{ return stash(ACCEPT_FROM_HOST_T); }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 240 "probeconfscan.l"
{ yylval.net_dir = SKPC_DIR_DST;
                                          return stash(NET_DIRECTION);}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 242 "probeconfscan.l"
{ return stash(END_GROUP_T); }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 243 "probeconfscan.l"
{ return stash(END_PROBE_T); }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 244 "probeconfscan.l"
{ return stash(END_SENSOR_T); }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 245 "probeconfscan.l"
{ return stash(GROUP_T); }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 246 "probeconfscan.l"
{ return stash(INCLUDE_T); }
	YY_BREAK
case 17:
/* rule 17 can match eol */
YY_RULE_SETUP
#line 247 "probeconfscan.l"
{ err_include_arg();BEGIN(ST_NEWLINE);}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 248 "probeconfscan.l"
{ return stash(INTERFACES_T); }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 249 "probeconfscan.l"
{ return stash(INTERFACE_VALUES_T); }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 250 "probeconfscan.l"
{ return stash(IPBLOCKS_T); }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 251 "probeconfscan.l"
{ return stash(ISP_IP_T); }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 252 "probeconfscan.l"
{ return stash(LISTEN_AS_HOST_T); }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 253 "probeconfscan.l"
{ return stash(LISTEN_ON_PORT_T); }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 254 "probeconfscan.l"
{ return stash(LISTEN_ON_USOCKET_T);}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 255 "probeconfscan.l"
{ return stash(LISTEN_ON_USOCKET_T);}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 256 "probeconfscan.l"
{ return stash(LOG_FLAGS_T); }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 257 "probeconfscan.l"
{ return stash(POLL_DIRECTORY_T); }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 258 "probeconfscan.l"
{ return stash(PRIORITY_T); }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 259 "probeconfscan.l"
{ return stash(PROBE_T); }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 260 "probeconfscan.l"
{ return stash(PROTOCOL_T); }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 261 "probeconfscan.l"
{ return stash(QUIRKS_T); }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 262 "probeconfscan.l"
{ return stash(READ_FROM_FILE_T); }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 263 "probeconfscan.l"
{ yylval.net_dir = SKPC_DIR_SRC;
                                          return stash(NET_DIRECTION); }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 265 "probeconfscan.l"
{ if (extra_sensor_verify_fn) {
                                              return stash(SENSOR_T);
                                          } else {
                                              BEGIN(ST_IGNORE_SENSOR);
                                        } }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 271 "probeconfscan.l"
{ yyless(0); BEGIN(ST_ERR); }
	YY_BREAK
/* go into the ST_FILTER state */
case 36:
YY_RULE_SETUP
#line 275 "probeconfscan.l"
{ filter_start('u'); }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 276 "probeconfscan.l"
{ filter_start('w'); }
	YY_BREAK
/* ST_FILTER state: handle the second keyword for "discard-when"
     * and "discard-unless" */
case 38:
YY_RULE_SETUP
#line 281 "probeconfscan.l"
{ return filter_set_type('a', 'n'); }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 282 "probeconfscan.l"
{ return filter_set_type('d', 'n'); }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 283 "probeconfscan.l"
{ return filter_set_type('s', 'n'); }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 285 "probeconfscan.l"
{ return filter_set_type('a', 'w'); }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 286 "probeconfscan.l"
{ return filter_set_type('d', 'w'); }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 287 "probeconfscan.l"
{ return filter_set_type('s', 'w'); }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 289 "probeconfscan.l"
{ yyless(0);
                                          filter_set_type('-', '-');
                                          BEGIN(ST_ERR); }
	YY_BREAK
/* ST_ARGS state: handle text after initial keyword */
case 45:
/* rule 45 can match eol */
YY_RULE_SETUP
#line 296 "probeconfscan.l"
{ BEGIN(ST_NEWLINE); return EOL; }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 298 "probeconfscan.l"
{ return REMAINDER_T; }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 300 "probeconfscan.l"
{ yylval.string = strdup(probeconfscan_text);
                                          return ID; }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 303 "probeconfscan.l"
{ BEGIN(ST_STRING);
                                          pcscan_buf_ptr = pcscan_buf; }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 306 "probeconfscan.l"
{ return COMMA; }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 308 "probeconfscan.l"
{ yyless(0); BEGIN(ST_ARG_ERR); }
	YY_BREAK
/* handle errors */
case 51:
YY_RULE_SETUP
#line 313 "probeconfscan.l"
{ err_bad_line(1); }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 315 "probeconfscan.l"
{ err_bad_line(0); }
	YY_BREAK
/* return EOL so the parser can throw away its current state */
case 53:
/* rule 53 can match eol */
YY_RULE_SETUP
#line 319 "probeconfscan.l"
{ BEGIN(ST_NEWLINE); return EOL; }
	YY_BREAK
/* ST_IGNORE_SENSOR state: ignore everything until we reach the
     * "end sensor" line. */
case 54:
/* rule 54 can match eol */
YY_RULE_SETUP
#line 325 "probeconfscan.l"
{ BEGIN(ST_NEWLINE);}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 326 "probeconfscan.l"
{ BEGIN(ST_ERR); }
	YY_BREAK
case 56:
/* rule 56 can match eol */
YY_RULE_SETUP
#line 327 "probeconfscan.l"
{ ++pcscan_file->line; }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 328 "probeconfscan.l"
;
	YY_BREAK
/* ST_STRING state: Accepts the remainder of a quoted string
     * (after the initial quote) and returns the value.  This is
     * pretty much equivalent to quoted strings in C. */
case 58:
YY_RULE_SETUP
#line 335 "probeconfscan.l"
{ BEGIN(ST_ARGS);
                          STRING_CHECK;
                          *pcscan_buf_ptr = '\0';
                          yylval.string = strdup(pcscan_buf);
                          return QUOTED_STRING; }
	YY_BREAK
case 59:
/* rule 59 can match eol */
YY_RULE_SETUP
#line 341 "probeconfscan.l"
{ BEGIN(ST_NEWLINE);
                          skpcParseErr("Quoted string missing closing quote");
                          return EOL; }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 345 "probeconfscan.l"
{ STRING_CHECK; *pcscan_buf_ptr++ = '\n'; }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 346 "probeconfscan.l"
{ STRING_CHECK; *pcscan_buf_ptr++ = '\t'; }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 347 "probeconfscan.l"
{ STRING_CHECK; *pcscan_buf_ptr++ = '\r'; }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 348 "probeconfscan.l"
{ STRING_CHECK; *pcscan_buf_ptr++ = '\b'; }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 349 "probeconfscan.l"
{ STRING_CHECK; *pcscan_buf_ptr++ = '\f'; }
	YY_BREAK
case 65:
/* rule 65 can match eol */
YY_RULE_SETUP
#line 350 "probeconfscan.l"
{ STRING_CHECK; *pcscan_buf_ptr++ = '\n'; }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 351 "probeconfscan.l"
{ STRING_CHECK; *pcscan_buf_ptr++ = probeconfscan_text[1]; }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 353 "probeconfscan.l"
{ if ((pcscan_buf_ptr + probeconfscan_leng) > pcscan_buf_end ) {
                              BEGIN(ST_ERR);
                              return ERR_STR_TOO_LONG;
                          }
                          memcpy(pcscan_buf_ptr, probeconfscan_text, probeconfscan_leng);
                          pcscan_buf_ptr += probeconfscan_leng; }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 360 "probeconfscan.l"
ECHO;
	YY_BREAK
#line 1631 "probeconfscan.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(ST_ARGS):
case YY_STATE_EOF(ST_FILTER):
case YY_STATE_EOF(ST_ERR):
case YY_STATE_EOF(ST_ARG_ERR):
case YY_STATE_EOF(ST_STRING):
case YY_STATE_EOF(ST_NEWLINE):
case YY_STATE_EOF(ST_IGNORE_SENSOR):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed probeconfscan_in at a new source and called
			 * probeconfscan_lex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = probeconfscan_in;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_last_accepting_cpos);
				yy_current_state = (yy_last_accepting_state);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( probeconfscan_wrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * probeconfscan_text, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of probeconfscan_lex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					probeconfscan_realloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			probeconfscan_restart(probeconfscan_in  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) probeconfscan_realloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 459 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 459 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 458);

	return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			yy_size_t offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					probeconfscan_restart(probeconfscan_in );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( probeconfscan_wrap( ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve probeconfscan_text */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void probeconfscan_restart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        probeconfscan_ensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            probeconfscan__create_buffer(probeconfscan_in,YY_BUF_SIZE );
	}

	probeconfscan__init_buffer(YY_CURRENT_BUFFER,input_file );
	probeconfscan__load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void probeconfscan__switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		probeconfscan_pop_buffer_state();
	 *		probeconfscan_push_buffer_state(new_buffer);
     */
	probeconfscan_ensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	probeconfscan__load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (probeconfscan_wrap()) processing, but the only time this flag
	 * is looked at is after probeconfscan_wrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void probeconfscan__load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	probeconfscan_in = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE probeconfscan__create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) probeconfscan_alloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in probeconfscan__create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) probeconfscan_alloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in probeconfscan__create_buffer()" );

	b->yy_is_our_buffer = 1;

	probeconfscan__init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with probeconfscan__create_buffer()
 * 
 */
    void probeconfscan__delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		probeconfscan_free((void *) b->yy_ch_buf  );

	probeconfscan_free((void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a probeconfscan_restart() or at EOF.
 */
    static void probeconfscan__init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	probeconfscan__flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then probeconfscan__init_buffer was _probably_
     * called from probeconfscan_restart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void probeconfscan__flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		probeconfscan__load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void probeconfscan_push_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	probeconfscan_ensure_buffer_stack();

	/* This block is copied from probeconfscan__switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from probeconfscan__switch_to_buffer. */
	probeconfscan__load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void probeconfscan_pop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	probeconfscan__delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		probeconfscan__load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void probeconfscan_ensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)probeconfscan_alloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in probeconfscan_ensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)probeconfscan_realloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in probeconfscan_ensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE probeconfscan__scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) probeconfscan_alloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in probeconfscan__scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	probeconfscan__switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to probeconfscan_lex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       probeconfscan__scan_bytes() instead.
 */
YY_BUFFER_STATE probeconfscan__scan_string (yyconst char * yystr )
{
    
	return probeconfscan__scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to probeconfscan_lex() will
 * scan from a @e copy of @a bytes.
 * @param bytes the byte buffer to scan
 * @param len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE probeconfscan__scan_bytes  (yyconst char * yybytes, yy_size_t  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n, i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) probeconfscan_alloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in probeconfscan__scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = probeconfscan__scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in probeconfscan__scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up probeconfscan_text. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		probeconfscan_text[probeconfscan_leng] = (yy_hold_char); \
		(yy_c_buf_p) = probeconfscan_text + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		probeconfscan_leng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current token.
 * 
 */

int probeconfscan_get_debug  (void)
{
        return probeconfscan__flex_debug;
}

void probeconfscan_set_debug (int  bdebug )
{
        probeconfscan__flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from probeconfscan_lex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    probeconfscan_in = stdin;
    probeconfscan_out = stdout;
#else
    probeconfscan_in = (FILE *) 0;
    probeconfscan_out = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * probeconfscan_lex_init()
     */
    return 0;
}

/* probeconfscan_lex_destroy is for both reentrant and non-reentrant scanners. */
int probeconfscan_lex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		probeconfscan__delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		probeconfscan_pop_buffer_state();
	}

	/* Destroy the stack itself. */
	probeconfscan_free((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * probeconfscan_lex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *probeconfscan_alloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *probeconfscan_realloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void probeconfscan_free (void * ptr )
{
	free( (char *) ptr );	/* see probeconfscan_realloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 360 "probeconfscan.l"



SK_DIAGNOSTIC_IGNORE_POP("-Wwrite-strings")

int
probeconfscan_wrap(void)
{
    switch (YY_START) {
      case ST_NEWLINE:
        /* this is what we expect */
        break;
      case ST_IGNORE_SENSOR:
        skpcParseErr("Missing \"end sensor\" or final newline");
        break;
      case ST_STRING:
        skpcParseErr("Quoted string missing closing quote");
        break;
      default:
        skpcParseErr("Missing final newline or"
                     " incomplete statement at end-of-file");
        BEGIN(ST_NEWLINE);
        break;
    }
    return skpcParseIncludePop();
}


/*
 *  stash(int)
 *
 *      Stash the current keyword (using the probeconfscan_leng and probeconfscan_text
 *      globals), put us into a ST_ARGS start-state, and return the
 *      value we were passed.
 */
static int
stash(
    int                 tok)
{
    /* make certain the keyword fits in our buffer */
    assert(probeconfscan_leng < ((int)sizeof(pcscan_clause)));

    /* copy it in */
    strncpy(pcscan_clause, probeconfscan_text, sizeof(pcscan_clause));

    /* we're processing the arguments */
    BEGIN(ST_ARGS);

    /* return whatever we were passed */
    return tok;
}


/*
 *  string = get_name(input_string, c);
 *
 *    Allocate and return a copy of 'input_string' up to (but not
 *    including) the character 'c'.  If 'input_string' does not
 *    contain 'c', return a copy of the entire string.
 */
static char *
get_name(
    const char         *s,
    int                 c)
{
    const char *cp = strrchr(s, c);
    char *sp;

    if (cp == NULL) {
        return strdup(s);
    }
    sp = (char*)malloc(1 + (cp - s));
    if (sp) {
        strncpy(sp, s, (cp - s));
        sp[(cp - s)] = '\0';
    }
    return sp;
}


/*
 *  filter_start(unless_when);
 *
 *    Handle the "discard-when" and "discard-unless" keywords, and
 *    stash the keyword.  'unless_when' should be 'u' if this is a
 *    "discard-unless" keyword, and a 'w' for "discard-when".  Prepare
 *    to handle the next keyword describing what to
 *    discard-unless/when and the type of data.
 */
static void
filter_start(
    char                unless_when)
{
    /* copy keyword into the pcscan_clause */
    strncpy(pcscan_clause, probeconfscan_text, sizeof(pcscan_clause));

    /* initialize filter */
    memset(&yylval.filter, 0, sizeof(skpc_filter_t));

    switch (unless_when) {
      case 'u':
        yylval.filter.f_discwhen = 0;
        break;
      case 'w':
        yylval.filter.f_discwhen = 1;
        break;
      default:
        skpcParseErr("Invalid unless_when '%c'", unless_when);
        skAbort();
    }

    BEGIN(ST_FILTER);
}


/*
 *  filter_set_type(filter_type, list_type);
 *
 *    Handle the second keyword in a "discard-when" or
 *    "discard-unless" statement.  Append this additional text to the
 *    'pcscan_clause' used to report errors.
 *
 *    'filter_type' specifies the first character of the second
 *    keyword ('a'ny, 'd'estination, 's'source), and it determines the
 *    skpc_filter_type_t.
 *
 *    'list_type' is 'n' for numbers (interfaces) or 'w' for wildcards
 *    (ipblocks).
 *
 *    A 'filter_type' of '-' indicates an error parsing the keyword
 *    following the discard-when/discard-unless statement.
 */
static int
filter_set_type(
    char                filter_type,
    char                list_type)
{
    if ('-' == filter_type) {
        /* invalid keyword */
        skpcParseErr("Missing or invalid type for %s", pcscan_clause);
        return -1;
    }

    /* append text into pcscan_clause */
    strncat(pcscan_clause, " ",
            (sizeof(pcscan_clause) - strlen(pcscan_clause) - 1));
    strncat(pcscan_clause, probeconfscan_text,
            (sizeof(pcscan_clause) - strlen(pcscan_clause) - 1));

    switch (filter_type) {
      case 'a':
        yylval.filter.f_type = SKPC_FILTER_ANY;
        break;
      case 'd':
        yylval.filter.f_type = SKPC_FILTER_DESTINATION;
        break;
      case 's':
        yylval.filter.f_type = SKPC_FILTER_SOURCE;
        break;
      default:
        skpcParseErr("Invalid filter_type '%c'", filter_type);
        skAbort();
    }
    switch (list_type) {
      case 'n':                 /* interface numbers */
        yylval.filter.f_wildcard = 0;
        break;
      case 'w':                 /* ipblock wildcards */
        yylval.filter.f_wildcard = 1;
        break;
      default:
        skpcParseErr("Invalid list_type '%c'", list_type);
        skAbort();
    }

    /* prepare to grab the interfaces or ipblocks */
    BEGIN(ST_ARGS);
    return FILTER;
}


/*
 *  err_bad_line(is_id);
 *
 *    Called when the scanner reads a bad line of input.  This
 *    function prints an error and increases the global error count.
 *
 *    If 'is_id' is 0, we have a single uknown character; otherwise we
 *    have a bad keyword.  At this point probeconfscan_text holds the entire bad
 *    line.
 */
static void
err_bad_line(
    int                 is_id)
{
    size_t i;

    /* Make sure the parser lets the application know that things failed. */
    ++pcscan_errors;

    /* Handle a bad character; this is easy */
    if (is_id == 0) {
        skpcParseErr("Unexpected character '%c'", probeconfscan_text[0]);
        return;
    }

    /* Handle a bad keyword.  Copy the first keyword into
     * pcscan_clause[] so we can print it. */
    for (i = 0; i < sizeof(pcscan_clause)-1; ++i) {
        /* This switch has the same character classes as our {idchar}. */
        switch (probeconfscan_text[i]) {
          case '\0':
            goto END_WORD;
          case '-':
          case '.':
          case '_':
          case '/':
            pcscan_clause[i] = probeconfscan_text[i];
            break;
          default:
            if (isalnum((int)probeconfscan_text[i])) {
                pcscan_clause[i] = probeconfscan_text[i];
            } else {
                goto END_WORD;
            }
            break;
        }
    }
  END_WORD:
    pcscan_clause[i] = '\0';

    skpcParseErr("Unrecognized keyword '%s'", pcscan_clause);
}


/*
 *  err_include_arg();
 *
 *    Print a message about the argument to include statement.
 */
static void
err_include_arg(
    void)
{
    /* Make sure the parser lets the application know that things failed. */
    ++pcscan_errors;

    skpcParseErr("Argument to include must be in \"double quotes\"");
}


#ifndef TEST_PRINTF_FORMATS
int
skpcParseErr(
    const char         *fmt,
    ...)
{
    va_list args;

    va_start(args, fmt);
    if (pcscan_file != NULL && pcscan_file->name != NULL) {
        fprintf(stderr, "%s: Error while parsing file %s at line %d:\n\t",
                skAppName(), pcscan_file->name, pcscan_file->line);
    } else {
        fprintf(stderr, "%s: Error during parsing [no current file]:\n\t",
                skAppName());
    }
    vfprintf(stderr, fmt, args);
    fprintf(stderr, "\n");
    va_end(args);
    return 0;
}
#endif  /* TEST_PRINTF_FORMATS */


static int
skpcParseOpenFile(
    char               *filename)
{
    pcscan_file_t *new_file;
    const char *action_name =
        ((pcscan_stack_depth == 0) ? "read sensor-config" : "include");

    if (filename == NULL) {
        goto ERROR;
    }

    if (!skFileExists(filename)) {
        if (0 == pcscan_stack_depth) {
            skAppPrintErr(("Cannot %s '%s': "
                           "File does not exist or is not a regular file"),
                          action_name, filename);
        } else {
            skpcParseErr(("Cannot %s '%s': "
                          "File does not exist or is not a regular file"),
                         action_name, filename);
        }
        goto ERROR;
    }

    if (pcscan_stack_depth >= PCSCAN_MAX_INCLUDE_DEPTH) {
        skpcParseErr("Cannot include file '%s': includes nested too deeply",
                     filename);
        goto ERROR;
    }

    new_file = &pcscan_stack[pcscan_stack_depth];
    new_file->name = filename;
    new_file->line = 0;

    /* open the file */
    new_file->fp = fopen(new_file->name, "r");
    if (!new_file->fp) {
        skpcParseErr("Cannot %s '%s': %s",
                     action_name, filename, strerror(errno));
        goto ERROR;
    }

    /* set up scanner */
    new_file->state = probeconfscan__create_buffer(new_file->fp,YY_BUF_SIZE);
    probeconfscan__switch_to_buffer(new_file->state);

    /* success */
    pcscan_file = new_file;
    ++pcscan_stack_depth;
    BEGIN(ST_NEWLINE);

    return 0;

  ERROR:
    if (filename) {
        free(filename);
    }
    return -1;
}


int
skpcParseIncludePop(
    void)
{
    if (pcscan_stack_depth == 0) {
        return 1;
    }

    /* free current state */
    probeconfscan__delete_buffer(YY_CURRENT_BUFFER);
    fclose(pcscan_file->fp);
    free(pcscan_file->name);

    /* pop to previous state; if no more states, we're done */
    --pcscan_stack_depth;
    if (pcscan_stack_depth == 0) {
        pcscan_file = NULL;
        return 1;
    }

    pcscan_file = &(pcscan_stack[pcscan_stack_depth-1]);
    probeconfscan__switch_to_buffer(pcscan_file->state);

    /* let processing continue */
    return 0;
}


int
skpcParseIncludePush(
    char               *filename)
{
    return skpcParseOpenFile(filename);
}


int
skpcParse(
    const char         *filename,
    int               (*site_verify_sensor_fn)(skpc_sensor_t *sensor))
{
    /* store the site-specific sensor-verify function */
    extra_sensor_verify_fn = site_verify_sensor_fn;

    /* clear the error count */
    pcscan_errors = 0;

    /* initialize the include stack */
    pcscan_stack_depth = 0;

    /* send in a copy so we can free it */
    if (skpcParseOpenFile(strdup(filename))) {
        return -1;
    }

    /* parse */
    (void)yyparse();

    /* return non-zero if we had errors */
    if (pcscan_errors > 0) {
        return -1;
    }

    return 0;
}


/*
** Local Variables:
** mode:c
** indent-tabs-mode:nil
** c-basic-offset:4
** End:
*/

